CREATE TABLE "country_section_mappings" (
  "id" TEXT PRIMARY KEY,
  "country_code" TEXT NOT NULL,
  "superset_code" TEXT NOT NULL,
  "heading" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX "country_section_mappings_country_code_superset_code_key" ON "country_section_mappings" ("country_code", "superset_code");

INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'EU', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CH', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'FR', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'DE', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SE', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ES', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PL', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BR', '01. Title', 'Título da Invenção');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UAE', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IL', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'US', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IN', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PK', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BD', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'AU', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'NZ', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UK', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CA', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CN', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'KR', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'TW', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IR', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MY', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'JP', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'RU', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MX', '01. Title', 'Título de la Invención');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SA', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ZA', '01. Title', 'Title of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'EU', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CH', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'FR', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'DE', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SE', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ES', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PL', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BR', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UAE', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IL', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'US', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IN', '02. Preamble', 'The following specification particularly describes...');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PK', '02. Preamble', 'The following specification particularly describes...');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BD', '02. Preamble', 'The following specification particularly describes...');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'AU', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'NZ', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UK', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CA', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CN', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'KR', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'TW', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IR', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MY', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'JP', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'RU', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MX', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SA', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ZA', '02. Preamble', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'EU', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CH', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'FR', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'DE', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SE', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ES', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PL', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BR', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UAE', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IL', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'US', '03. Cross-Ref/Fed', 'Cross-Reference... / Gov. License Rights');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IN', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PK', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BD', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'AU', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'NZ', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UK', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CA', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CN', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'KR', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'TW', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IR', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MY', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'JP', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'RU', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MX', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SA', '03. Cross-Ref/Fed', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'EU', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CH', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'FR', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'DE', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SE', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ES', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PL', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BR', '04. Tech Field', 'Campo da Invenção');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UAE', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IL', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'US', '04. Tech Field', 'Field of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IN', '04. Tech Field', 'Field of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PK', '04. Tech Field', 'Field of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BD', '04. Tech Field', 'Field of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'AU', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'NZ', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UK', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CA', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CN', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'KR', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'TW', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IR', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MY', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'JP', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'RU', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MX', '04. Tech Field', 'Campo Técnico');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SA', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ZA', '04. Tech Field', 'Technical Field');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'EU', '05. Background', 'Background Art');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CH', '05. Background', 'Background Art');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'FR', '05. Background', 'Background Art');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'DE', '05. Background', 'Background Art');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SE', '05. Background', 'Background Art');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ES', '05. Background', 'Background Art');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PL', '05. Background', 'Background Art');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BR', '05. Background', 'Fundamentos da Invenção');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UAE', '05. Background', 'Background Art');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IL', '05. Background', 'Background Art');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'US', '05. Background', 'Background of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IN', '05. Background', 'Background of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PK', '05. Background', 'Background of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BD', '05. Background', 'Background of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'AU', '05. Background', 'Background of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'NZ', '05. Background', 'Background of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UK', '05. Background', 'Background of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CA', '05. Background', 'Background of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CN', '05. Background', 'Background Art');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'KR', '05. Background', 'Background Art');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'TW', '05. Background', 'Background Art');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IR', '05. Background', 'Background Art');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MY', '05. Background', 'Background Art');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'JP', '05. Background', 'Background Art');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'RU', '05. Background', 'Background Art');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MX', '05. Background', 'Antecedentes de la Invención');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SA', '05. Background', 'Background Art');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ZA', '05. Background', 'Background of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'EU', '06. Objects', '(Recommended/NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CH', '06. Objects', '(Recommended/NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'FR', '06. Objects', '(Recommended/NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'DE', '06. Objects', '(Recommended/NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SE', '06. Objects', '(Recommended/NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ES', '06. Objects', '(Recommended/NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PL', '06. Objects', '(Recommended/NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BR', '06. Objects', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UAE', '06. Objects', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IL', '06. Objects', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'US', '06. Objects', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IN', '06. Objects', 'Object(s) of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PK', '06. Objects', 'Object(s) of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BD', '06. Objects', 'Object(s) of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'AU', '06. Objects', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'NZ', '06. Objects', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UK', '06. Objects', '(Recommended)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CA', '06. Objects', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CN', '06. Objects', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'KR', '06. Objects', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'TW', '06. Objects', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IR', '06. Objects', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MY', '06. Objects', '(Recommended/NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'JP', '06. Objects', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'RU', '06. Objects', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MX', '06. Objects', 'Objetivo de la invención');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SA', '06. Objects', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ZA', '06. Objects', '(Recommended/NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'EU', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CH', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'FR', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'DE', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SE', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ES', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PL', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BR', '07. Summary (Gen)', 'Sumário da Invenção');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UAE', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IL', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'US', '07. Summary (Gen)', 'Brief Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IN', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PK', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BD', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'AU', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'NZ', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UK', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CA', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CN', '07. Summary (Gen)', 'Summary of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'KR', '07. Summary (Gen)', 'Content of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'TW', '07. Summary (Gen)', 'Content of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IR', '07. Summary (Gen)', 'Summary of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MY', '07. Summary (Gen)', 'Summary of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'JP', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'RU', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MX', '07. Summary (Gen)', 'Breve Resumen de la Invención');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SA', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ZA', '07. Summary (Gen)', 'Summary of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'EU', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CH', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'FR', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'DE', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SE', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ES', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PL', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BR', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UAE', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IL', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'US', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IN', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PK', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BD', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'AU', '07a. Tech Problem', '(Recommended)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'NZ', '07a. Tech Problem', '(Recommended)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UK', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CA', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CN', '07a. Tech Problem', 'Technical Problem');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'KR', '07a. Tech Problem', 'Technical Problem');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'TW', '07a. Tech Problem', 'Technical Problem');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IR', '07a. Tech Problem', 'Technical Problem');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MY', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'JP', '07a. Tech Problem', 'Technical Problem');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'RU', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MX', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SA', '07a. Tech Problem', '(Recommended)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ZA', '07a. Tech Problem', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'EU', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CH', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'FR', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'DE', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SE', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ES', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PL', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BR', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UAE', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IL', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'US', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IN', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PK', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BD', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'AU', '07b. Tech Solution', '(Recommended)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'NZ', '07b. Tech Solution', '(Recommended)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UK', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CA', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CN', '07b. Tech Solution', 'Technical Solution');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'KR', '07b. Tech Solution', 'Technical Solution');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'TW', '07b. Tech Solution', 'Technical Solution');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IR', '07b. Tech Solution', 'Technical Solution');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MY', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'JP', '07b. Tech Solution', 'Solution to Problem');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'RU', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MX', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SA', '07b. Tech Solution', '(Recommended)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ZA', '07b. Tech Solution', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'EU', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CH', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'FR', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'DE', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SE', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ES', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PL', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BR', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UAE', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IL', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'US', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IN', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PK', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BD', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'AU', '07c. Effects', '(Recommended)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'NZ', '07c. Effects', '(Recommended)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UK', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CA', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CN', '07c. Effects', 'Advantageous Effects');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'KR', '07c. Effects', 'Advantageous Effects');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'TW', '07c. Effects', 'Advantageous Effects');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IR', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MY', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'JP', '07c. Effects', 'Advantageous Effects of Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'RU', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MX', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SA', '07c. Effects', '(Recommended)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ZA', '07c. Effects', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'EU', '08. Drawings', 'Brief Description of Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CH', '08. Drawings', 'Brief Description of Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'FR', '08. Drawings', 'Brief Description of Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'DE', '08. Drawings', 'Brief Description of Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SE', '08. Drawings', 'Brief Description of Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ES', '08. Drawings', 'Brief Description of Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PL', '08. Drawings', 'Brief Description of Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BR', '08. Drawings', 'Breve Descrição dos Desenhos');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UAE', '08. Drawings', 'Brief Description of Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IL', '08. Drawings', 'Brief Description of Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'US', '08. Drawings', 'Brief Description of the Several Views of the Drawing');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IN', '08. Drawings', 'Brief Description of the Accompanying Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PK', '08. Drawings', 'Brief Description of the Accompanying Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BD', '08. Drawings', 'Brief Description of the Accompanying Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'AU', '08. Drawings', 'Brief Description of the Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'NZ', '08. Drawings', 'Brief Description of the Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UK', '08. Drawings', 'Brief Description of the Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CA', '08. Drawings', 'Brief Description of the Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CN', '08. Drawings', 'Brief Description of Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'KR', '08. Drawings', 'Brief Description of Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'TW', '08. Drawings', 'Brief Description of Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IR', '08. Drawings', 'Brief Description of Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MY', '08. Drawings', 'Brief Description of Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'JP', '08. Drawings', 'Brief Description of Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'RU', '08. Drawings', 'Brief Description of the Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MX', '08. Drawings', 'Breve Descripción de las Figuras');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SA', '08. Drawings', 'Brief Description of Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ZA', '08. Drawings', 'Brief Description of the Drawings');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'EU', '09. Detailed Desc', 'Detailed Description (or "Description of Embodiments")');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CH', '09. Detailed Desc', 'Detailed Description (or "Description of Embodiments")');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'FR', '09. Detailed Desc', 'Detailed Description (or "Description of Embodiments")');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'DE', '09. Detailed Desc', 'Detailed Description (or "Description of Embodiments")');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SE', '09. Detailed Desc', 'Detailed Description (or "Description of Embodiments")');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ES', '09. Detailed Desc', 'Detailed Description (or "Description of Embodiments")');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PL', '09. Detailed Desc', 'Detailed Description (or "Description of Embodiments")');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BR', '09. Detailed Desc', 'Descrição Detalhada da Invenção');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UAE', '09. Detailed Desc', 'Detailed Description');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IL', '09. Detailed Desc', 'Detailed Description');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'US', '09. Detailed Desc', 'Detailed Description of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IN', '09. Detailed Desc', 'Detailed Description of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PK', '09. Detailed Desc', 'Detailed Description of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BD', '09. Detailed Desc', 'Detailed Description of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'AU', '09. Detailed Desc', 'Description of Embodiments');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'NZ', '09. Detailed Desc', 'Description of Embodiments');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UK', '09. Detailed Desc', 'Detailed Description');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CA', '09. Detailed Desc', 'Detailed Description');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CN', '09. Detailed Desc', 'Specific Mode for Carrying Out the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'KR', '09. Detailed Desc', 'Detailed Description of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'TW', '09. Detailed Desc', 'Detailed Description of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IR', '09. Detailed Desc', 'Detailed Description');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MY', '09. Detailed Desc', 'Detailed Description');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'JP', '09. Detailed Desc', 'Detailed Description of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'RU', '09. Detailed Desc', 'Detailed Description of the Invention');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MX', '09. Detailed Desc', 'Descripción Detallada');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SA', '09. Detailed Desc', 'Detailed Description');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ZA', '09. Detailed Desc', 'Detailed Description');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'EU', '10. Best Mode', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CH', '10. Best Mode', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'FR', '10. Best Mode', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'DE', '10. Best Mode', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SE', '10. Best Mode', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ES', '10. Best Mode', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PL', '10. Best Mode', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BR', '10. Best Mode', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UAE', '10. Best Mode', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IL', '10. Best Mode', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'US', '10. Best Mode', 'Best Mode (NA in Desc)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IN', '10. Best Mode', '(Include in Detailed Desc)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PK', '10. Best Mode', '(Include in Detailed Desc)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BD', '10. Best Mode', '(Include in Detailed Desc)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'AU', '10. Best Mode', 'Best Method of Performance');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'NZ', '10. Best Mode', 'Best Method of Performance');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UK', '10. Best Mode', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CA', '10. Best Mode', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CN', '10. Best Mode', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'KR', '10. Best Mode', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'TW', '10. Best Mode', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IR', '10. Best Mode', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MY', '10. Best Mode', 'Best Mode');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'JP', '10. Best Mode', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'RU', '10. Best Mode', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MX', '10. Best Mode', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SA', '10. Best Mode', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ZA', '10. Best Mode', 'Best Method of Performance');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'EU', '11. Ind. Applicability', 'Industrial Applicability');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CH', '11. Ind. Applicability', 'Industrial Applicability');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'FR', '11. Ind. Applicability', 'Industrial Applicability');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'DE', '11. Ind. Applicability', 'Industrial Applicability');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SE', '11. Ind. Applicability', 'Industrial Applicability');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ES', '11. Ind. Applicability', 'Industrial Applicability');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PL', '11. Ind. Applicability', 'Industrial Applicability');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BR', '11. Ind. Applicability', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UAE', '11. Ind. Applicability', '(Required if not obvious)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IL', '11. Ind. Applicability', '(Required if not obvious)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'US', '11. Ind. Applicability', '(N/A - Utility)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IN', '11. Ind. Applicability', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PK', '11. Ind. Applicability', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BD', '11. Ind. Applicability', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'AU', '11. Ind. Applicability', '(Recommended/NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'NZ', '11. Ind. Applicability', '(Recommended/NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UK', '11. Ind. Applicability', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CA', '11. Ind. Applicability', '(N/A)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CN', '11. Ind. Applicability', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'KR', '11. Ind. Applicability', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'TW', '11. Ind. Applicability', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IR', '11. Ind. Applicability', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MY', '11. Ind. Applicability', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'JP', '11. Ind. Applicability', 'Industrial Applicability');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'RU', '11. Ind. Applicability', '(Required if needed)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MX', '11. Ind. Applicability', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SA', '11. Ind. Applicability', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ZA', '11. Ind. Applicability', '(NA)');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'EU', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CH', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'FR', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'DE', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SE', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ES', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PL', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BR', '12. Claims', 'Reivindicações');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UAE', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IL', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'US', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IN', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PK', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BD', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'AU', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'NZ', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UK', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CA', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CN', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'KR', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'TW', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IR', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MY', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'JP', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'RU', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MX', '12. Claims', 'Reivindicaciones');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SA', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ZA', '12. Claims', 'Claims');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'EU', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CH', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'FR', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'DE', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SE', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ES', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PL', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BR', '13. Abstract', 'Resumo');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UAE', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IL', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'US', '13. Abstract', 'Abstract of the Disclosure');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IN', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'PK', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'BD', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'AU', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'NZ', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'UK', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CA', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'CN', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'KR', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'TW', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'IR', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MY', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'JP', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'RU', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'MX', '13. Abstract', 'Resumen');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'SA', '13. Abstract', 'Abstract');
INSERT INTO "country_section_mappings" ("id", "country_code", "superset_code", "heading") VALUES (md5(random()::text || clock_timestamp()::text), 'ZA', '13. Abstract', 'Abstract');
