CREATE TABLE "country_names" ("code" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(), "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('EU', 'European Union', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('CH', 'Switzerland', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('FR', 'France', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('DE', 'Germany', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('SE', 'Sweden', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('ES', 'Spain', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('PL', 'Poland', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('BR', 'Brazil', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('UAE', 'United Arab Emirates', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('IL', 'Israel', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('US', 'United States of America', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('IN', 'India', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('PK', 'Pakistan', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('BD', 'Bangladesh', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('AU', 'Australia', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('NZ', 'New Zealand', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('UK', 'United Kingdom', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('CA', 'Canada', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('CN', 'China', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('JP', 'Japan', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('KR', 'South Korea', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('TW', 'Taiwan', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('IR', 'Iran', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('MY', 'Malaysia', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('RU', 'Russia', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('MX', 'Mexico', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('SA', 'Saudi Arabia', NOW(), NOW());
INSERT INTO "country_names" ("code", "name", "created_at", "updated_at") VALUES ('ZA', 'South Africa', NOW(), NOW());
