-- Add SEARCH_STRATEGY to FeatureCode enum
ALTER TYPE "FeatureCode" ADD VALUE IF NOT EXISTS 'SEARCH_STRATEGY';

-- Add SEARCH_STRATEGY_GEN to TaskCode enum  
ALTER TYPE "TaskCode" ADD VALUE IF NOT EXISTS 'SEARCH_STRATEGY_GEN';

